services:
  secret-phrase:
    containers:
      nextjs:
        resources:
          limits:
            cpu: 2800m
            memory: 2G
          requests:
            cpu: 700m
            memory: 1000M
        image: secret-phrase
    scaling:
      min: 1
      max: 2
      targetcpu: 80
mesh:
  enabled: true
  hostname: secret-phrase.cbhq.net
