enableTelemetry: false

nodeLinker: node-modules

packageExtensions:
  "@testing-library/jest-dom@*":
    peerDependencies:
      vitest: "*"
    peerDependenciesMeta:
      vitest:
        optional: true

yarnPath: .yarn/releases/yarn-4.8.1.cjs
