enableTelemetry: false

nodeLinker: node-modules

npmRegistryServer: "https://npm-proxy.cbhq.net"

npmScopes:
  cbhq:
    npmRegistryServer: "https://npm-proxy.cbhq.net"

packageExtensions:
  "@testing-library/jest-dom@*":
    peerDependencies:
      vitest: "*"
    peerDependenciesMeta:
      vitest:
        optional: true

yarnPath: .yarn/releases/yarn-4.8.1.cjs
