enableTelemetry: false

nodeLinker: node-modules

npmRegistryServer: "https://npm-proxy.cbhq.net"

npmScopes:
  cbhq:
    npmRegistryServer: "https://npm-proxy.cbhq.net"

yarnPath: .yarn/releases/yarn-4.8.1.cjs
