apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: placeholder-name
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: placeholder-org-placeholder-name
      app.kubernetes.io/component: placeholder-name
  strategy:
    blueGreen:
      activeService: placeholder-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: placeholder-org-placeholder-name
        app.kubernetes.io/component: placeholder-name
    spec:
      # Disable multi-arch support and pin all K8 pods to ARM. This ensures that all pods are running on the same architecture. Not doing
      # this can result in incidents as explained here: https://confluence.coinbase-corp.com/spaces/SL/pages/1733473093/Multi-Arch+Next.js+Deployment+Issues
      tolerations:
      - key: "infra.coinbase.com/arch"
        operator: "Equal"
        value: "arm"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
      containers:
        - image: {{ index .Values "services" "placeholder-name" "containers" "nextjs" "image" }}
          name: nextjs
          ports:
            - containerPort: 3001
          startupProbe:
            httpGet:
              path: /api/health
              port: 3001
            initialDelaySeconds: 60 # wait 60 seconds to start probing
            periodSeconds: 10 # probe every 10 seconds
            failureThreshold: 30 # allow 30 failures (5 minutes of boot time)
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            limits:
              cpu: {{ index .Values "services" "placeholder-name" "containers" "nextjs" "resources" "limits" "cpu" }}
              memory: {{ index .Values "services" "placeholder-name" "containers" "nextjs" "resources" "limits" "memory" }}
            requests:
              cpu: {{ index .Values "services" "placeholder-name" "containers" "nextjs" "resources" "requests" "cpu" }}
              memory: {{ index .Values "services" "placeholder-name" "containers" "nextjs" "resources" "requests" "memory" }}
      restartPolicy: Always
